apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend
 labels:
   app: backend
spec:
 replicas: 1
 selector:
   matchLabels:
     app: backend
 template:
   metadata:
     labels:
       app: backend
   spec:
     containers:
     - name: app
       image: doreg.azurecr.io/backend/prod:latest
       imagePullPolicy: Always
       ports:
       - containerPort: 8000